# Generated by Django 4.1.9 on 2023-06-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_collection', '0002_remove_image_collection_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='file_name',
        ),
        migrations.AlterField(
            model_name='image_collection',
            name='key_points',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
